#!/bin/sh /etc/rc.common
# Derived from OpenWrt sing-box package; SPDX-License-Identifier: GPL-2.0-only
USE_PROCD=1
START=99
PROG=/usr/bin/sing-box
start_service() {
    config_load sing-box
    local enabled user conffile workdir ifaces group
    config_get_bool enabled main enabled 0
    [ "$enabled" -eq 1 ] || return 0
    config_get user main user root
    config_get conffile main conffile /etc/sing-box/config.json
    config_get workdir main workdir /usr/share/sing-box
    config_get ifaces main ifaces
    mkdir -p "$workdir"
    group="$(id -ng "$user")" || return 1
    chown "$user:$group" "$workdir"
    procd_open_instance sing-box.main
    procd_set_param command "$PROG" run -c "$conffile" -D "$workdir"
    procd_set_param user "$user"
    procd_set_param file "$conffile"
    [ -z "$ifaces" ] || procd_set_param netdev $ifaces
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param respawn
    procd_close_instance
}
service_triggers() {
    local ifaces iface
    config_load sing-box
    config_get ifaces main ifaces
    procd_open_trigger
    for iface in $ifaces; do
        procd_add_interface_trigger 'interface.*.up' "$iface" /etc/init.d/sing-box restart
    done
    procd_close_trigger
    procd_add_reload_trigger sing-box
}
